### ISSUE TITLE
Rust - Break down ockam crate dependency in ockam_transport_tcp

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1160]
Currently, the `ockam_transport_tcp` crate [depends on the ockam crate](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/Cargo.toml#L26).

We would like to break this dependency and have the `ockam_transport_tcp` crate depend on `ockam_core` and which ever other supporting crates, instead of the top level `ockam` crate.

This allows better composition of the optional modules for end users.

**Comment by jared-s** [comment]
@spacekookie this might be relevant to refactors you are working on next week I hear maybe?

**Comment by spacekookie** [comment]
I thought the reason that `ockam_transport_tcp` depended on the `ockam` crate was to be able to use the same switchable node-logic as any user application (i.e. switch the node implementation that is used by `ockam_transport_tcp`). In reality this may not work though, because the current tcp transport is very tightly coupled to tokio, which wouldn't run in a `no_std` environment.

Anyway, decoupling these two things and creating an explicit dependency from `ockam_transport_tcp` to `ockam_node` may not be a bad thing.

**Comment by jared-s** [comment]
@SanjoDeundiak untangled this - thanks!
