### ISSUE TITLE
Rust - 08-routing-transport-many-hops-middle panics

### ISSUE THREAD

**Issue by jared-s** [ockam-network/ockam#1259]
The change in https://github.com/ockam-network/ockam/commit/1290ad472eeea726377e4408163fe63c6248e527 to use per `Address` random addresses instead of the default static address, seems to have broken [this example](https://github.com/ockam-network/ockam/blob/develop/examples/rust/get_started/examples/08-routing-over-transport-many-hops-middle.rs).

~~I've verified locally that restoring the default address behavior causes this program to work again, but I doubt that is the right solution.~~

Update: Reverting the address change alone is not sufficient..it's some other change in that commit.

cc @spacekookie

**Comment by spacekookie** [comment]
Oh woops, no this is a trivial fix. I forgot to update the getting started example to the new TCP transport API :see_no_evil: 

The following code creates _two_ tcp routers, the second of which fails to initialise because there is already a tcp address type router in the system.

```rust
    TcpTransport::create_listener(&ctx, "127.0.0.1:4000").await?;
    TcpTransport::create(&ctx, "127.0.0.1:6000").await?;
```

This code creates one Transport/ router and then uses it to initialise an outgoing connection.

```rust
    let tcp = TcpTransport::create_listener(&ctx, "127.0.0.1:4000").await?;
    tcp.connect("127.0.0.1:6000").await?;
```

This feels like a common foot gun so I'll document the function endpoints better. We should probably also mention this in the guides.
