### ISSUE TITLE
Need to throttle data transmission rate over network

### ISSUE THREAD

**Issue by robinbudd** [ockam-network/ockam#660]
We need a mechanism to throttle data transmission rate. Currently, when the IP stack's internal buffers are exhausted, a send request fails with "WouldBlock", which causes a panic.

**Comment by gpicron** [comment]
Hi.  I'm looking at ockam for the first time today, so I may be totally wrong.  Forget it if I am.

Looking at the rust implementation in rs directory, I think you may reach similar problem even between Workers within the same process.  The issue, I think, is that the Node loop and MessageRouter loop are acting as some kind runtime job scheduler but do not prevent a handler to flood the enqueue_message_ref of messages and doesn't try to implements any kind of fair scheduling. 
So that if you have one worker pushing rapidly a lot of messages, first you may blow the memory or simply make the node unresponsive (especially because there is a single message queue per node).
Similarly, any IO may block and make the node unresponsive.

I suppose that you are trying to keep the design as simple and avoid copies because usually most of the "agent-like" frameworks use bounded mpsc mailboxes to dispatch messages and schedule messages and a separate IO thread pool.

I think I have maybe an idea that modify a bit your design without increasing too much the complexity, a bit inspired from Pull Stream framework.  The idea would be that tail ProcessMessage implementors returns not only a bool (ongoing) but how much they still can process immediately.  The EnqueueMessage would be a bit more complex containing a register of credits per target address and higher dispatching layers ( node, message_router, tcp_manager, etc.) could then keep that register up-to-date (based last returns from tails).

Does it make sense ?
